### PR TITLE
dracut: parse coreos.oem.id for ignition

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by crawford** [comment]
Fixes https://github.com/coreos/bugs/issues/933.
Related to https://github.com/coreos/coreos-overlay/pull/1592.

**Comment by vcaputo** [comment]
lgtm

**Comment by marineam** [comment]
Is ignition going to handle mounting OEM itself if it finds an oem url scheme?

**Comment by vcaputo** [comment]
yes

**Comment by marineam** [comment]
LGTM :)

**Pull request merged**
