### PR TITLE
dracut: include ca-certs bundle

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by crawford** [comment]
/cc @gtank @mjg59 

This pulls the ca-cert bundle into the initrd so that Ignition can fetch HTTPS.

**Comment by marineam** [comment]
inst_simple follows the symlink right?

It is worth noting that this is sufficent for Go but not openssl which isn't configured to read the all-in-one cert bundle. Honestly it really should, the directory of cert hashes is a truly shitty setup that we inherited. But that's for another day.

**Comment by crawford** [comment]
Yes, it follows symlinks. I was able to point Ignition at a gist (HTTPS only).

**Comment by marineam** [comment]
LGTM

**Pull request merged**
